### ISSUE TITLE
Status bar is causing stalls when opening files

### ISSUE THREAD

**Issue by adepke** [kemayo/sublime-text-git#584]
When I open files in my `.config/sublime-text/Packages/User` folder (a git repo), I'm seeing 2+ second freezes. Here's what my Plugin Event Profile shows:
```
on_activated:
    Git.git.ignore: 0.005s total, mean: 0.000s, max: 0.000s
    Git.git.statusbar: 4.716s total, mean: 0.030s, max: 2.325s
    ...
```
